#!/bin/bash

#
# Copyright 2016-09 brett.chaldecott@gmail.com
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#

# setup environment variables
LS_BASE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# imports
. ${LS_BASE_DIR}/lib/env.sh

# setup the default arguments
lstacker_command="unknown"
lstacker_file="./lstacker.yml"

# parse the arguments
for key in "$@" ; do
	case $key in
		-f|--file)
			lstacker_file="$2"
			shift # past argument
			;;
		stack)
			lstacker_command=$key
			;;
		unstack)
			lstacker_command=$key
			;;
		help)
			lstacker_command=$key
			;;
		version)
			lstacker_command=$key
			;;
		create)
			lstacker_command=$key
			lstacker_host="$2"
			lstacker_container="$3"
			shift # past argument
			;;
		destroy)
			lstacker_command=$key
			lstacker_host="$2"
			lstacker_container="$3"
			shift # past argument
			;;
		*)
			# unknown option
			;;
	esac
	shift # past argument or value
done


# execute the command
execute_command
